-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsQgtXIZadsFpJogU
 OyHTKhlor4SPSmj/nmMbYVHq7oKgCgYIKoZIzj0DAQehRANCAASqisAeoaV6fUs
 1 hrd2MZx4AhJHG0viUq4aKpHqq7vzX+tjHhPefESIimLCxQP3M3RO04QreOms5
 3 lN CAZzArkF
-----END PRIVATE KEY-----